# Generated by Django 5.1.1 on 2024-10-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='full_name',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
