# Generated by Django 5.1.1 on 2024-10-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
        migrations.DeleteModel(
            name='RegisterModel',
        ),
    ]
