# Generated by Django 5.1.1 on 2024-10-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offersmodel',
            options={'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterField(
            model_name='offersmodel',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='offers_title'),
        ),
    ]
