# Generated by Django 5.1.1 on 2024-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_offersmodel_options_alter_offersmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offersmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offersmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='offers_title'),
        ),
        migrations.AddField(
            model_name='offersmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='offers_title'),
        ),
    ]
