# Generated by Django 5.1.2 on 2024-10-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_aboutsectionmodel_homepagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSectionModel',
        ),
        migrations.DeleteModel(
            name='HomePageModel',
        ),
        migrations.AlterModelOptions(
            name='problemsmodel',
            options={'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
        migrations.AddField(
            model_name='problemsmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problemsmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problemsmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problemsmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
