# Generated by Django 5.1.2 on 2024-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_delete_aboutsectionmodel_delete_homepagemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsmodel',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='problems_title'),
        ),
        migrations.AlterField(
            model_name='problemsmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='problems_title'),
        ),
        migrations.AlterField(
            model_name='problemsmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='problems_title'),
        ),
    ]
