# Generated by Django 5.1.1 on 2024-10-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_offersmodel_description_ru_offersmodel_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersmodel',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offersmodel',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offersmodel',
            name='description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offersmodel',
            name='description_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
