# Generated by Django 5.1.1 on 2024-10-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_offersmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offersmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offersmodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offersmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
    ]
