# Generated by Django 5.1.1 on 2024-10-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_alter_offersmodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='about_site_title')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Site',
                'verbose_name_plural': 'About Sites',
            },
        ),
    ]
