# Generated by Django 5.1.1 on 2024-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_aboutsitemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsitemodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsitemodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsitemodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsitemodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='about_site_title'),
        ),
        migrations.AddField(
            model_name='aboutsitemodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='about_site_title'),
        ),
        migrations.AddField(
            model_name='aboutsitemodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='about_site_title'),
        ),
    ]
