# Generated by Django 5.1.1 on 2024-10-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_questionmodel_teamaboutmodul'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='question_title'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='question_title'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='question_title'),
        ),
        migrations.AddField(
            model_name='teamaboutmodul',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teamaboutmodul',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teamaboutmodul',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teamaboutmodul',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='team_about_module_title'),
        ),
        migrations.AddField(
            model_name='teamaboutmodul',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='team_about_module_title'),
        ),
        migrations.AddField(
            model_name='teamaboutmodul',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='team_about_module_title'),
        ),
    ]
