# Generated by Django 5.1.1 on 2024-10-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_questionmodel_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamaboutmodul',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_avatars/', verbose_name='Profile Image'),
        ),
    ]
