# Generated by Django 5.1.1 on 2024-10-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_alter_teamaboutmodul_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamaboutmodul',
            name='role',
            field=models.CharField(max_length=50, null=True, verbose_name='team_about_role'),
        ),
    ]
