# Generated by Django 5.1.1 on 2024-10-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_teamaboutmodul_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealsModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='appeals_module_title')),
                ('role', models.CharField(max_length=255, null=True, verbose_name='role_title')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appeals Module',
                'verbose_name_plural': 'Appeals Modules',
            },
        ),
        migrations.RemoveField(
            model_name='teamaboutmodul',
            name='role',
        ),
    ]
