# Generated by Django 5.1.1 on 2024-10-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_appealsmodule_remove_teamaboutmodul_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealsmodule',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appealsmodule',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appealsmodule',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appealsmodule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appeals_images/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='appealsmodule',
            name='role_en',
            field=models.CharField(max_length=255, null=True, verbose_name='role_title'),
        ),
        migrations.AddField(
            model_name='appealsmodule',
            name='role_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='role_title'),
        ),
        migrations.AddField(
            model_name='appealsmodule',
            name='role_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='role_title'),
        ),
        migrations.AddField(
            model_name='appealsmodule',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='appeals_module_title'),
        ),
        migrations.AddField(
            model_name='appealsmodule',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='appeals_module_title'),
        ),
        migrations.AddField(
            model_name='appealsmodule',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='appeals_module_title'),
        ),
        migrations.AlterField(
            model_name='appealsmodule',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='appeals_module_title'),
        ),
    ]
