# Generated by Django 5.1.1 on 2024-10-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_alter_teamaboutmodul_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamaboutmodul',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teamaboutmodul',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teamaboutmodul',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teamaboutmodul',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
